In [2]:
import numpy as np

Q = np.array([3, 5, 8])

enc1 = np.array([3, 2, -8])
enc2 = np.array([1, -2, 5])
enc3 = np.array([3, 6, 9])

#enc = enc1
#enc = enc.append(enc2)
#enc = enc.append(enc3)

enc = np.array([[3, 2, -8], [1, -2, 5], [3, 6, 9]])

In [5]:
s_input = enc.dot(Q)
print(s_input)

[-45  33 111]


In [6]:
print(np.dot(enc, Q))

[-45  33 111]


In [3]:
from scipy.special import softmax

logits = [0, 1, -1]
s_z = softmax(logits)

print(s_z)

[0.24472847 0.66524096 0.09003057]


In [11]:
decoder_input = enc.dot(s_z)
print(decoder_input)

[ 1.34442274 -0.63560057  5.53590631]


In [19]:
print(s_z.dot(enc))

[ 1.66951809 -0.30084153  2.17865217]


In [4]:
np.dot(s_z, enc)

array([ 1.66951809, -0.30084153,  2.17865217])

In [12]:
np.dot(enc, s_z)

array([ 1.34442274, -0.63560057,  5.53590631])

In [27]:
aa = np.array([1, 0.5])
bb = np.array([[1,-1], [1,2]])
print(bb.dot(aa))

[0.5 2. ]


In [29]:
np.dot(bb, aa)

array([0.5, 2. ])

In [30]:
a = np.array([0.18, 0.82])
b = np.array([[1,-1], [1,2]])
print(a.dot(b))

[1.   1.46]


In [31]:
np.dot(a,b)

array([1.  , 1.46])

In [16]:
print(b.dot(a))

[-0.64  1.82]


In [18]:
np.dot(b,a)

array([-0.64,  1.82])